SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS fact_proyecto_beneficiario_poai_2024;
DROP TABLE IF EXISTS fact_proyecto_institucion_poai_2024;
DROP TABLE IF EXISTS fact_proyecto_meta_poai_2024;
DROP TABLE IF EXISTS fact_actividades_poai_2024;
DROP TABLE IF EXISTS dim_institucion_poai_2024;
DROP TABLE IF EXISTS dim_municipio_poai_2024;
DROP TABLE IF EXISTS dim_actividad_poai_2024;
DROP TABLE IF EXISTS dim_meta_poai_2024;
DROP TABLE IF EXISTS dim_tiempo_poai_2024;
DROP TABLE IF EXISTS dim_proyecto_poai_2024;
DROP TABLE IF EXISTS dim_fuente_poai_2024;
SET FOREIGN_KEY_CHECKS=1;
